"""Initial revision

Revision ID: 684eab7949dc
Revises: 
Create Date: 2019-01-13 20:23:42.124673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684eab7949dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
